language: objective-c
osx_image: xcode10

env:
  global:
    - PROJECT='SFExtension.xcodeproj'
    - IOS_SCHEME='SFExtension-iOS'
    - MACOS_SCHEME='SFExtension-macOS'
    - IOS_DESTINATION='platform=iOS Simulator,name=iPhone X'
    - MACOS_DESTINATION='platform=OS X'

  # - ACTION=test  PLATFORM=Mac     DESTINATION='platform=OS X'
  # - ACTION=test  PLATFORM=iOS     DESTINATION='platform=iOS Simulator,name=iPhone X'
  # - ACTION=test  PLATFORM=tvOS    DESTINATION='platform=tvOS Simulator,name=Apple TV 1080p'
# before_install:
#   - bundle install
#   - gem install cocoapods --pre
#   - brew update
#   - brew outdated xctool || brew upgrade xctool
script:
  - set -o pipefail 
  - swift --version

  - xcodebuild clean test -project "$PROJECT" -scheme "$IOS_SCHEME" -destination "$IOS_DESTINATION" | xcpretty

  - xcodebuild clean test -project "$PROJECT" -scheme "$MACOS_SCHEME" -destination "$MACOS_DESTINATION" | xcpretty
  
  # - bundle exec danger --verbose
  # - pod lib lint
after_success:
    # - sleep 5
    - bash <(curl -s https://codecov.io/bash)
